# Generated by Django 3.2.4 on 2021-07-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20210717_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
