# Generated by Django 3.2.4 on 2021-07-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_storecity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(default=0)),
                ('seller_id', models.IntegerField(default=0)),
                ('buyer_id', models.IntegerField(default=0)),
                ('tax', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
