# Generated by Django 3.2.4 on 2021-07-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(default='In Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='$', max_length=5),
        ),
    ]
