# Generated by Django 3.2.4 on 2021-07-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_auto_20210721_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('seller_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('shipping_type', models.CharField(default='', max_length=30)),
                ('national_shipping_fee', models.CharField(default='', max_length=10)),
                ('national_free_shipping_fee', models.CharField(default='', max_length=10)),
                ('national_free_shipping_enabled', models.CharField(default='', max_length=5)),
                ('disable_national_shipping', models.CharField(default='', max_length=5)),
                ('international_shipping_fee', models.CharField(default='', max_length=10)),
                ('international_free_shipping_fee', models.CharField(default='', max_length=10)),
                ('international_free_shipping_enabled', models.CharField(default='', max_length=5)),
                ('disable_international_shipping', models.CharField(default='', max_length=5)),
                ('product_handling_fee', models.CharField(default='', max_length=10)),
                ('shipping_country', models.CharField(default='', max_length=20)),
                ('shipping_address', models.CharField(default='', max_length=500)),
                ('shipping_city', models.CharField(default='', max_length=20)),
                ('shipping_state', models.CharField(default='', max_length=20)),
                ('shipping_postcode', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='facebook_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='instagram_username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='linkedin_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='pinterest_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='snapchat_username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='telegram_username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='twitter_username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='youtube_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='user_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
