# Generated by Django 3.2.4 on 2021-07-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_store_terms_and_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatabase',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='userdatabase',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='userdatabase',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='userdatabase',
            name='pinterest_url',
        ),
        migrations.RemoveField(
            model_name='userdatabase',
            name='snapchat_username',
        ),
        migrations.RemoveField(
            model_name='userdatabase',
            name='telegram_username',
        ),
        migrations.RemoveField(
            model_name='userdatabase',
            name='twitter_username',
        ),
        migrations.RemoveField(
            model_name='userdatabase',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='store',
            name='facebook_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram_username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='linkedin_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='pinterest_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='snapchat_username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='telegram_username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='twitter_username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='youtube_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
