# Generated by Django 3.2.4 on 2021-07-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_auto_20210722_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='membership_status',
            field=models.CharField(default='inactive', max_length=50),
        ),
    ]
