# Generated by Django 3.2.4 on 2021-07-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_store_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='membership_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
