# Generated by Django 3.2.4 on 2021-07-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0025_alter_store_membership_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='membership_start_date',
        ),
    ]
