# Generated by Django 3.2.4 on 2021-07-22 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0027_store_membership_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default='')),
                ('discount_type', models.CharField(default='', max_length=50)),
                ('apply_to_all_products', models.BooleanField(default=False)),
                ('coupon_amount', models.CharField(max_length=10)),
                ('allow_free_shipping', models.BooleanField(default=False)),
                ('coupon_expiry', models.DateField(default=datetime.date.today)),
                ('minimum_spend', models.CharField(default='', max_length=10)),
                ('maximum_spend', models.CharField(default='', max_length=10)),
                ('individual_use_only', models.BooleanField(default=False)),
                ('exclude_sale_item', models.BooleanField(default=False)),
                ('restricted_emails', models.CharField(default='', max_length=500)),
                ('usage_limit_per_coupon', models.IntegerField(default=100)),
                ('usage_limit_item', models.IntegerField(default=100)),
                ('usage_limit_per_user', models.IntegerField(default=100)),
                ('seller_id', models.IntegerField(default=0)),
            ],
        ),
    ]
