# Generated by Django 3.2.4 on 2021-07-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0028_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
