# Generated by Django 3.2.4 on 2021-07-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0029_store_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
