# Generated by Django 3.2.4 on 2021-07-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0030_usercomment_userreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
