# Generated by Django 3.2.4 on 2021-07-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0031_auto_20210724_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
