# Generated by Django 3.2.4 on 2021-07-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0034_alter_cart_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_id', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
            ],
        ),
    ]
