# Generated by Django 3.2.4 on 2021-07-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0037_buyerbillingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPaymentDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_id', models.IntegerField(default=0)),
                ('card_number', models.CharField(default='', max_length=30)),
                ('expiry', models.CharField(default='', max_length=10)),
                ('cvv', models.CharField(default='', max_length=5)),
            ],
        ),
    ]
