# Generated by Django 3.2.4 on 2021-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0038_buyerpaymentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPaymentDetail',
            fields=[
                ('seller_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('stripe_public_key', models.CharField(default='', max_length=500)),
                ('stripe_private_key', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='BuyerPaymentDetail',
        ),
    ]
