# Generated by Django 3.2.4 on 2021-07-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0039_auto_20210728_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerpaymentdetail',
            name='paypal_client_id',
        ),
        migrations.RemoveField(
            model_name='sellerpaymentdetail',
            name='stripe_private_key',
        ),
        migrations.RemoveField(
            model_name='sellerpaymentdetail',
            name='stripe_public_key',
        ),
        migrations.AddField(
            model_name='sellerpaymentdetail',
            name='bank_BIC_SWIFT',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sellerpaymentdetail',
            name='bank_IBAN',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sellerpaymentdetail',
            name='bank_account_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sellerpaymentdetail',
            name='bank_account_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sellerpaymentdetail',
            name='bank_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sellerpaymentdetail',
            name='bank_routing_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sellerpaymentdetail',
            name='paypal_address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
