# Generated by Django 3.2.4 on 2021-07-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0041_auto_20210728_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_id',
            field=models.IntegerField(default=0),
        ),
    ]
