# Generated by Django 3.2.4 on 2021-07-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0042_order_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_paypal',
            field=models.CharField(default='', max_length=100),
        ),
    ]
