# Generated by Django 3.2.4 on 2021-07-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0043_auto_20210729_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTaxRules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_percentage', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
