# Generated by Django 3.2.4 on 2021-07-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0045_auto_20210729_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
