# Generated by Django 3.2.4 on 2021-07-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0047_auto_20210729_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_membership_price', models.CharField(default='9.99', max_length=10)),
                ('monthly_membership_price', models.CharField(default='4.99', max_length=10)),
            ],
        ),
    ]
