# Generated by Django 3.2.4 on 2021-07-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0048_membershipprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='user_type',
            field=models.CharField(default='BUYER', max_length=50),
        ),
    ]
