# Generated by Django 3.2.4 on 2021-07-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0049_auto_20210729_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='support/images')),
                ('category', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
