# Generated by Django 3.2.4 on 2021-08-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0052_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(default=0)),
                ('product_quantity', models.IntegerField(default=0)),
                ('session_id', models.IntegerField(default=0)),
            ],
        ),
    ]
