# Generated by Django 3.2.4 on 2021-08-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0053_guestcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpaymentdetail',
            name='paypal_key',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='order_notes',
            field=models.TextField(default=''),
        ),
    ]
