from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('login/', views.loginPage, name='loginPage'),
    path('support/', views.supportPage, name='supportPage'),
    path('buyer-information/', views.buyerTerms, name='buyerTerms'),
    path('seller-information/', views.sellerTerms, name='sellerTerms'),
    path('refund-policy/', views.refundPolicy, name='refundPolicy'),
    path('password-reset/', views.passwordReset, name='passwordReset'),
    path('dashboard/', views.dashboard, name='Dashboard'),
    path('orders/', views.ordersPage, name='ordersPage'),
    path('subscriptions/', views.subscriptionsPage, name='subscriptionsPage'),
    path('downloads/', views.downloadsPage, name='downloadsPage'),
    path('address/', views.addressPage, name='addressPage'),
    path('payment-method/', views.paymentMethodPage, name='paymentMethodPage'),
    path('account/', views.accountPage, name='accountPage'),
    path('become-seller/', views.becomeSellerPage, name='becomeSellerPage'),
    path('user/signup/', views.handleSignup, name='handleSignup'),
    path('logout/', views.logoutUser, name='logoutUser'),
    path('user/login/', views.loginUser, name='loginUser'),
    path('pro-dashboard/', views.proDashboard, name='proDashboard'),
    path('pro-products/', views.proProducts, name='proProducts'),
    path('add-product/', views.addProduct, name='addProduct'),
    path('pro-orders/', views.proOrders, name='proOrders'),
    path('pro-settings/', views.proSettings, name='proSettings'),
    path('pro-payments/', views.proPayments, name='proPayments'),
    path('pro-branding/', views.proBranding, name='proBranding'),
    path('pro-shipping/', views.proShipping, name='proShipping'),
    path('category/', views.categoryPage, name='categoryPage'),
]